//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by OPCBClient.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_OPCBCLTYPE                  129
#define IDD_DIAG_SERVERS                131
#define IDD_DIALOG_EDIT                 132
#define IDD_DIAG_BROWSER                133
#define IDD_DIALOG_PARAM_RESULTS        134
#define IDD_DIALOG_FILTER               135
#define IDC_LIST_SERVER                 1000
#define IDC_RADIO1                      1001
#define IDC_RADIO2                      1002
#define IDC_RADIO3                      1003
#define IDC_EDIT_STATION                1004
#define IDC_EDIT_GENERAL                1005
#define IDC_EDIT_LABEL                  1006
#define IDC_ITEMID                      1007
#define IDC_EDIT_ITEMID                 1007
#define IDC_OPTION1                     1008
#define IDC_CHECK_PARAMETERS            1008
#define IDC_OPTION2                     1009
#define IDC_CHECK_RESULTS               1009
#define IDC_OPTION3                     1010
#define IDC_RADIO_ANONYMOUS             1011
#define IDC_BATCHID                     1012
#define IDC_DESCR                       1013
#define IDC_MINSIZE                     1014
#define IDC_MAXSIZE                     1015
#define IDC_MODEL_SELECT                1016
#define IDC_CHECK_UNFILTERED            1017
#define ID_FILE_CONNECT                 32771
#define ID_OPTIONS_VERBOSEOUTPUT        32772
#define ID_OPTIONS_SHOWPATH             32773
#define ID_TEST_IUNKNOWN_QUERYINTERFACE 32774
#define ID_TEST_IUNKNOWN_ADDREF         32775
#define ID_TEST_IUNKNOWN_RELEASE        32776
#define ID_TEST_IOPCCOMMON_SETLOCALEID  32777
#define ID_TEST_IOPCCOMMON_GETLOCALEID  32778
#define ID_TEST_IOPCCOMMON_QUERYAVAILABLELOCALIDS 32779
#define ID_TEST_IOPCCOMMON_QUERYAVAILABLELOCALEIDS 32780
#define ID_TEST_IOPCCOMMON_GETERRORSTRING 32781
#define ID_TEST_IOPCCOMMON_SETCLIENTNAME 32782
#define ID_TEST_IOPCSERVER_ADDGROUP     32783
#define ID_TEST_IOPCSERVER_GETERRORSTRING 32784
#define ID_TEST_IOPCSERVER_GETGROUPBYNAME 32785
#define ID_TEST_IOPCSERVER_REMOVEGROUP  32786
#define ID_TEST_IOPCSERVER_CREATEGROUPENUMERATOR 32787
#define ID_TEST_IOPCSERVER_GETSTATUS    32788
#define ID_TEST_IOPCSERVER_CREATEENUMERATOR 32789
#define ID_TEST_IOPCBROWSESERVERADDRESSSPACE_QUERYORGANIZATION 32791
#define ID_TEST_IOPCBROWSESERVERADDRESSSPACE_CHANGEBROWSEPOSITION 32792
#define ID_TEST_IOPCBROWSESERVERADDRESSSPACE_BROWSEOPCITEMIDS 32793
#define ID_TEST_IOPCBROWSESERVERADDRESSSPACE_GETITEMID 32794
#define ID_TEST_IOPCBROWSESERVERADDRESSSPACE_BROWSEACCESSPATHS 32795
#define ID_TEST_IPERSISTFILE_ISDIRTY    32796
#define ID_TEST_IPERSISTFILE_LOAD       32797
#define ID_TEST_IPERSISTFILE_SAVE       32798
#define ID_TEST_IPERSISTFILE_SAVECOMPLETED 32799
#define ID_TEST_IPERSISTFILE_GETCURFILENAME 32800
#define ID_TEST_ICONNECTIONPOINTCONTAINER_ENUMCONNECTIONPOINTS 32801
#define ID_TEST_ICONNECTIONPOINTCONTAINER_FINDCONNECTIONPOINT 32802
#define ID_TEST_IOPCITEMPROPERTIES_QUERYAVAILABLEPROPERTIES 32803
#define ID_TEST_IOPCITEMPROPERTIES_GETITEMPROPERTIES 32804
#define ID_TEST_IOPCITEMPROPERTIES_LOOKUP 32805
#define ID_TEST_IOPCITEMPROPERTIES_LOOKUPITEMIDS 32806
#define ID_TEST_IOPCENUMERATIONSETS_QUERYENUMERATIONSETS 32807
#define ID_TEST_IOPCENUMERATIONSETS_QUERYENUMERATION 32808
#define ID_TEST_IOPCENUMERATIONSETS_QUERYENUMERATIONLIST 32809
#define ID_TEST_IENUMOPCBATCHSUMMARY_NEXT 32810
#define ID_TEST_IENUMOPCBATCHSUMMARY_SKIP 32811
#define ID_TEST_IENUMOPCBATCHSUMMARY_RESET 32812
#define ID_TEST_IENUMOPCBATCHSUMMARY_CLONE 32813
#define ID_TEST_IOPCSERVERPUBLICGROUPS_GETPUBLICGROUPBYNAME 32814
#define ID_TEST_IOPCSERVERPUBLICGROUPS_REMOVEPUBLICGROUP 32815
#define ID_FILE_CONNECTTOSERVER         32816
#define ID_TEST_UNADVISE                32817
#define ID_TEST_IOPCBATCHSERVER_GETSTATUS 32818
#define ID_TEST_IOPCBATCHSERVER_CREATEENUMERATOR 32819
#define ID_VIEW_CLEAR                   32820
#define ID_VIEW_SCROLLDOWN              32821
#define ID_TEST_IOPCBROWSESERVERADDRESSSPACE_SHOWTREE 32822
#define ID_OPTIONS_LOGTOFILE            32823
#define ID_TEST_IOPCBROWSESERVERADDRESSSPACE_PARAMETERS 32824
#define ID_TEST_IOPCBROWSESERVERADDRESSSPACE_RESULTS 32825
#define ID_TEST_IOPCBATCHSERVER_GETDELIMITER 32826
#define ID_TEST_PARAMETERS_RESULTS      32827
#define ID_TEST_IOPCBATCHSERV2_CREATEFILTENUM 32829

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32830
#define _APS_NEXT_CONTROL_VALUE         1018
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
